---
- name: "Gather facts playbook"
  hosts: "all"
  tasks:
    - name: "gathering facts"
      ansible.builtin.gather_facts:

    - name: "debug"
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"

