---
- name: "00: Create vim plug directories"
  ansible.builtin.file:
    path: "/home/{{ system_user }}/.vim/autoload"
    state: "directory"
    recurse: True

- name: "10: Download vim plug files"
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "/home/{{system_user }}/.vim/autoload/plug.vim"
