- name: "00: Upload the wireguard public and private keys to Hashicorp vault"
  delegate_to: "127.0.0.1"
  ansible.builtin.uri:
    url: "https://{{ lookup('ansible.builtin.env', 'SECRETS_PROVIDER_URL') }}/v1/kv/data/{{ name }}_WG_KEYPAIR"
    method: "POST"
    body_format: "json"
    headers:
       Authorization: "Bearer {{ lookup('ansible.builtin.env', 'SECRETS_PROVIDER_API_KEY')}}"
    body:
      data:
        public: "{{ vpn_public_key_content }}"
        secret: "{{ vpn_private_key_content }}"
        type: "wireguard"
