---
- name: "00: Create Public and Private server keys"
  become: True
  ansible.builtin.shell:
    command: "wg genkey | sudo tee /etc/wireguard/privatekey | wg pubkey | sudo tee /etc/wireguard/publickey"


  



